# Generated by Grok

import json
import numpy as np

# Example parameters for linspace
params = {"start": 0, "stop": 10, "num": 100, "endpoint": True, "dtype": "float64"}

# Save parameters to a JSON file
with open("linspace_params.json", "w") as f:
    json.dump(params, f)

# Later, to load and use these parameters:
with open("linspace_params.json", "r") as f:
    loaded_params = json.load(f)

linspace_array = np.linspace(**loaded_params)

print(linspace_array)
