# Part of the code is generated by Grok2
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Prevent segmentation fault
plt.switch_backend("Tkagg")

# Generate random data for example
data = np.random.rand(10, 10)
correlation_matrix = np.corrcoef(data)
df = pd.DataFrame(
    correlation_matrix,
    index=[rf"$\rho_{i}$" for i in range(10)],
    columns=[rf"$\Pi_{i}$" for i in range(10)],
)

# Create and display heatmap
fig = plt.figure(dpi=600)
fig.set_figwidth(6)
fig.set_figheight(4.8)
fig.set_size_inches(8, 5)  # Set the size in inches
sns.heatmap(
    df,
    annot=True,
    cmap="viridis",
    fmt=".2f",
)
plt.title(rf"$𝑝_𝑖 Tr(𝜌_𝑖 Π_𝑖 )$")
plt.savefig(fname=f"seaborn_heatmap.png", bbox_inches="tight")
plt.close()
