# Generated by Grok

from skopt import gp_minimize
import numpy as np

# Example objective function
def objective_function(params):
    x, y = params
    return (x - 2) ** 2 + (y - 3) ** 2  # Simple quadratic function

# Early stopping callback
class EarlyStopping:
    def __init__(self, patience=10, tol=1e-4):
        self.patience = patience  # Number of iterations without improvement
        self.tol = tol  # Minimum improvement threshold
        self.best_value = np.inf
        self.best_iter = 0
        self.current_iter = 0
        self.best_params = None

    def __call__(self, res):
        self.current_iter += 1
        current_value = res.fun  # Current objective value

        # Check if the current value is better than the best seen so far
        if current_value < self.best_value - self.tol:
            self.best_value = current_value
            self.best_params = res.x
            self.best_iter = self.current_iter
        # Check if we should stop
        elif self.current_iter - self.best_iter >= self.patience:
            print(f"Early stopping at iteration {self.current_iter}. Best value: {self.best_value}")
            raise StopIteration  # Raising StopIteration stops the optimization

# Define the search space
space = [(-5.0, 5.0), (-5.0, 5.0)]  # Search space for x and y

# Run gp_minimize with early stopping
early_stopper = EarlyStopping(patience=10, tol=1e-4)
try:
    res = gp_minimize(
        objective_function,
        space,
        n_calls=100,  # Maximum number of calls
        callback=[early_stopper],
        random_state=42
    )
except StopIteration:
    print("Optimization stopped early.")
    print(f"Best parameters: {early_stopper.best_params}")
    print(f"Best objective value: {early_stopper.best_value}")