# Generated by Grok

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np

plt.switch_backend("Tkagg")

# Create data for a surface plot
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

# Make data
X = np.arange(-5, 5, 0.25)
Y = np.arange(-5, 5, 0.25)
X, Y = np.meshgrid(X, Y)
R = np.sqrt(X**2 + Y**2)
Z = np.sin(R)

# Plot the surface with heatmap-like coloring
surf = ax.plot_surface(X, Y, Z, 
                       cmap='viridis',  # You can choose different colormaps: 'viridis', 'plasma', 'inferno', 'magma', 'cividis'
                       edgecolor='none')  # Remove edges to give a smoother look

# Customize the z axis
ax.set_zlim(-1.01, 1.01)

# Add a color bar which maps values to colors
cbar = fig.colorbar(surf, shrink=0.5, aspect=5)
cbar.set_label('Z Value')  # Label for the colorbar

# Labeling axes
ax.set_xlabel('X Axis')
ax.set_ylabel('Y Axis')
ax.set_zlabel('Z Axis')

# Adjust the view angle
ax.view_init(elev=30., azim=60)  # Elevation and azimuth can be adjusted for better visualization

plt.savefig("3dplot_color.png")