# Generated by Grok 3
import subprocess
import os
from threading import Semaphore
from tqdm import tqdm

# Configuration
max_jobs = 20
semaphore = Semaphore(max_jobs)  # Limits concurrent processes

# Calculate total number of iterations
q_range = range(2, 6)    # 4 values (2, 3, 4, 5)
n_range = range(3, 4)    # 1 value (3)
seed_range = range(5)    # 5 values (0, 1, 2, 3, 4)
total_tasks = len(q_range) * len(n_range) * len(seed_range)  # 4 * 1 * 5 = 20

# Initialize progress bar
processes = []  # To keep track of running processes

with tqdm(total=total_tasks, desc="Experiment Progress") as pbar:
    for q in q_range:
        for n in n_range:
            for seed in seed_range:
                # Define filenames and arguments consistently
                profile_output = f"profile_output_q{q}_n{n}_s{seed}.prof"
                log_file = f"20250223_q{q}_n{n}_s{seed}.log"
                args = [
                    "python", "-m", "cProfile", "-s", "cumtime", "-o", profile_output,
                    "flow/experiments.py", "-n", str(n), "-q", str(q), "-s", str(seed)
                ]

                # Use semaphore to manage concurrency
                with semaphore:  # Blocks if max_jobs is reached
                    # Launch process and redirect output
                    proc = subprocess.Popen(args, stdout=open(log_file, 'w'), stderr=subprocess.STDOUT)
                    processes.append(proc)

    # Wait for all processes and update progress bar
    for proc in processes:
        proc.wait()
        pbar.update(1)

print("All experiments completed!")