# Generated by qwen2.5-coder:32b
### 1. Incrementing Seeds
# You can simply increment the seeds for each test case.


import numpy as np


def generate_test_case(base_state_seed, base_noise_seed, num_cases):
    test_cases = []
    for i in range(num_cases):
        state_seed = base_state_seed + i
        noise_seed = base_noise_seed + i

        rng_state = np.random.default_rng(seed=state_seed)
        rng_noise = np.random.default_rng(seed=noise_seed)

        state = rng_state.normal(size=(10,))
        noise = rng_noise.normal(size=(10,))

        test_cases.append((state, noise))

    return test_cases


# Example usage
base_state_seed = 12345
base_noise_seed = 67890
num_cases = 5

test_cases = generate_test_case(base_state_seed, base_noise_seed, num_cases)

for i, (state, noise) in enumerate(test_cases):
    print(f"Test Case {i+1}:")
    print("State:", state)
    print("Noise:", noise)
    print()

### 2. Using a Hash Function
# You can use a hash function to generate seeds based on a unique identifier for each
# test case, such as the current time or a counter.

import numpy as np
import hashlib


def generate_seed(unique_id):
    return int(hashlib.md5(str(unique_id).encode()).hexdigest(), 16) % (2**32)


def generate_test_case(base_state_seed, base_noise_seed, num_cases):
    test_cases = []
    for i in range(num_cases):
        unique_state_id = f"state_{base_state_seed}_{i}"
        unique_noise_id = f"noise_{base_noise_seed}_{i}"

        state_seed = (generate_seed(unique_state_id) + base_state_seed) % (2**32)
        noise_seed = (generate_seed(unique_noise_id) + base_noise_seed) % (2**32)

        rng_state = np.random.default_rng(seed=state_seed)
        rng_noise = np.random.default_rng(seed=noise_seed)

        state = rng_state.normal(size=(10,))
        noise = rng_noise.normal(size=(10,))

        test_cases.append((state, noise))

    return test_cases


# Example usage
base_state_seed = 12345
base_noise_seed = 67890
num_cases = 5

test_cases = generate_test_case(base_state_seed, base_noise_seed, num_cases)

for i, (state, noise) in enumerate(test_cases):
    print(f"Test Case {i+1}:")
    print("State:", state)
    print("Noise:", noise)
    print()


### 3. Using a Random Seed Generator
# You can use a random seed generator to create unique seeds for each test case.

import numpy as np


def generate_test_case(base_state_seed, base_noise_seed, num_cases):
    rng_base = np.random.default_rng(seed=0)  # Base RNG to generate seeds

    test_cases = []
    for i in range(num_cases):
        state_seed = (rng_base.integers(0, 2**32) + base_state_seed) % (2**32)
        noise_seed = (rng_base.integers(0, 2**32) + base_noise_seed) % (2**32)

        rng_state = np.random.default_rng(seed=state_seed)
        rng_noise = np.random.default_rng(seed=noise_seed)

        state = rng_state.normal(size=(10,))
        noise = rng_noise.normal(size=(10,))

        test_cases.append((state, noise))

    return test_cases


# Example usage
base_state_seed = 12345
base_noise_seed = 67890
num_cases = 5

test_cases = generate_test_case(base_state_seed, base_noise_seed, num_cases)

for i, (state, noise) in enumerate(test_cases):
    print(f"Test Case {i+1}:")
    print("State:", state)
    print("Noise:", noise)
    print()

### Summary
## - **Incrementing Seeds**: Simple and straightforward, but may not be as robust for
## large numbers of test cases.
## - **Hash Function**: Provides a more unique seed based on a string identifier,
## ensuring less chance of collision.
## - **Random Seed Generator**: Uses a base RNG to generate seeds, providing a high
## degree of randomness.
## 
## Choose the method that best fits your needs. If you have any specific requirements
## or constraints, feel free to let me know!