# Explore different formulations to fit the distribution generated by the POVM
# derived by the noiseless problem.

import sys
import csv

sys.path.append("../")

from flow.solve_mix import *
from utils.handy_states import *


def sweep_FitQSD():
    # ## Define the input states

    state_dict = simple_2(0.2, 0.5, 0.7)
    num_qubits = state_dict["num_qubits"]
    num_states = state_dict["num_states"]
    state_vec = state_dict["state_vec"]
    dense_mat = [DensityMatrix(_) for _ in state_vec]

    qsd_problem = ProblemSpec(
        num_qubits=num_qubits,
        num_states=num_states,
        case_id="0809_test",
        state_type="densitymatrix",
    )

    noise_levels = [0.1 ** (6 - i) for i in range(6)]
    disturbance_states = [
        DensityMatrix(
            ProblemSpec.depolarizing_noise_channel(num_qubits=num_qubits)
        )
        for _ in range(num_states)
    ]

    # ## Compute the noiseless distribution

    n = qsd_problem.num_states
    # Comment/uncomment to switch between different prior probabilities
    prior_prob = np.ones(n) * (1 / n)
    # prior_prob = [1/9, 3/9, 5/9]
    qsd_problem.prior_prob = prior_prob

    qsd_problem.set_states(
        state_type="statevector",
        states=state_vec,
        overwrite=True,
    )
    ideal_result = apply_Eldar(
        problem_spec=qsd_problem,
        prior_prob=prior_prob,
        cvxpy_settings={
            "solver": cp.MOSEK,
            "verbose": False,
            "eps": 1e-8,
        },
    )

    ideal_distrib = calculate_prob_matrix_simple(
        prior_probs=prior_prob,
        povm=ideal_result["povm"],
        states=dense_mat,
    )
    print(ideal_result["p_succ"])

    # ## Use the POVM in noisy states

    def report_ideal(ideal_distrib):
        print("Ideal input states")
        print("POVM for ideal optimal UQSD")
        print(ideal_distrib)
        print()

    def dist_1(m):
        correct_results = [m[i][i] for i in range(len(m))]
        p_succ_ni = sum(correct_results)
        return np.concatenate((correct_results, np.array([1.0 - p_succ_ni])))

    def dist_2(m):
        measured_results = [
            sum([m[j][i] for j in range(len(m))]) for i in range(len(m))
        ]
        p_succ_ni = sum(measured_results)
        return np.concatenate((measured_results, np.array([1.0 - p_succ_ni])))

    def dist_3(m):
        """Yeah. No changes.
        However, we have to calculate the ideal distribution in the same way.
        """
        return np.array(m).flatten()

    def get_sqrt_dist(a, b):
        return np.sqrt(sum([abs(a[i] - b[i]) ** 2 for i in range(len(a))]))

    def report_noisy_states_with_ideal_povm(
        noise_level,
        ideal_distrib,
        qsd_problem: ProblemSpec,
        psucc_result,
    ):
        combined_states = [
            (1 - noise_level) * dense_mat[_]
            + noise_level * disturbance_states[_].data
            for _ in range(num_states)
        ]

        qsd_problem.set_states(
            state_type="densitymatrix",
            states=combined_states,
            overwrite=True,
        )
        # m is prob_matrix
        m = calculate_prob_matrix_simple(
            qsd_problem.prior_prob, ideal_result["povm"], combined_states
        )
        # for i in m:
        #     print(i)
        noisy_distrib_with_ideal_povm = dist_3(m)
        print(f"Noisy input states with depolarizing noise = {noise_level:3g}")
        print("POVM for ideal optimal UQSD")
        print(noisy_distrib_with_ideal_povm)
        np.set_printoptions(precision=4)
        psucc = 0
        for i in range(qsd_problem.num_states):
            psucc += m[i][i]
        print(psucc)

        print("alpha", np.array(calculate_errors(m)[0]))
        print("beta ", np.array(calculate_errors(m)[1]))

        psucc_result.append(psucc)
        sqrt_dist = get_sqrt_dist(
            np.array(ideal_distrib).flatten(), noisy_distrib_with_ideal_povm
        )
        print(
            f"Root sum of squares {np.format_float_scientific(sqrt_dist, precision=4)}"
        )
        print()

    sqrtd_result = []
    psucc_result = []
    for noise_level in noise_levels:
        report_noisy_states_with_ideal_povm(
            noise_level=noise_level,
            ideal_distrib=ideal_distrib,
            qsd_problem=qsd_problem,
            psucc_result=psucc_result,
        )

    # ## New formulations

    def run_qsd(
        qsd_problem: ProblemSpec,
        cvxpy_problem,
        sqrtd_result,
        psucc_result,
        eps=1e-8,
    ):
        cvxpy_settings = {
            "solver": cp.MOSEK,
            "verbose": False,
            # "verbose": True,
            # "requires_grad": True,
            # "mkl": True,
            "eps": eps,
            # "acceleration_lookback": 10,
            # "warm_start": True,
        }
        cvxpy_problem.solve(**cvxpy_settings)

        # print(cvxpy_problem.status)
        # print(cvxpy_problem.solution.opt_val)
        vars = cvxpy_problem.variables()

        fitqd_povm = [var.value for var in vars]
        # print(fitqd_povm)

        prob_mat = calculate_prob_matrix_simple(
            prior_probs=prior_prob,
            povm=fitqd_povm,
            states=qsd_problem.states,
        )
        # print(prob_mat)

        psucc = 0
        for i in range(qsd_problem.num_states):
            psucc += prob_mat[i][i]
        psucc_result.append(psucc)

        sqrt_dist = get_sqrt_dist(
            np.array(ideal_distrib).flatten(),
            np.array(prob_mat).flatten(),
        )
        sqrtd_result.append(sqrt_dist)
        #
        # print("alpha", np.array(calculate_errors(prob_mat)[0]))
        # print("beta ", max(calculate_errors(prob_mat)[1]))
        #
        # print()

    methods = [meco_problem, min_l1_problem, min_ss_problem]
    eps = 1e-9
    sqrtd_results = []
    psucc_results = []
    for method in methods:
        print(f"\n{method.__name__}")
        sqrtd_result = []
        psucc_result = []
        for noise_level in noise_levels:
            combined_states = [
                (1 - noise_level) * dense_mat[_]
                + noise_level * disturbance_states[_].data
                for _ in range(num_states)
            ]
            qsd_problem.set_states(
                state_type="densitymatrix",
                states=combined_states,
                overwrite=True,
            )
            # print("Noise level", np.format_float_scientific(noise_level, precision=4))
            cvxpy_problem = method(
                ideal_distrib=ideal_distrib,
                qsd_problem=qsd_problem,
                prior_prob=prior_prob,
            )
            run_qsd(
                qsd_problem=qsd_problem,
                cvxpy_problem=cvxpy_problem,
                sqrtd_result=sqrtd_result,
                psucc_result=psucc_result,
                eps=eps,
            )
        psucc_results.append(psucc_result)
        sqrtd_results.append(sqrtd_result)
        # --- 5. Write CSV ---
        with open("results/fitqsd_results.csv", "w", newline="") as f:
            writer = csv.writer(f)
            # header
            header = (
                ["lambda"]
                + [f"psucc_{name}" for name, _ in methods]
                + [f"L2_{name}" for name, _ in methods]
            )
            writer.writerow(header)

            # rows
            for idx, lam in enumerate(noise_levels):
                row = [lam]
                # psucc columns
                row += [psucc_result[name][idx] for name, _ in methods]
                # L2 columns
                row += [sqrtd_result[name][idx] for name, _ in methods]
                writer.writerow(row)

        # --- 6. Plot figure (left panel: P_succ, right panel: L2) ---
        fig, axes = plt.subplots(1, 2, figsize=(10, 3.5), dpi=300)

        # consistent styling: MinL1 red square, MinSS green dot, MECO blue triangle
        style_order = [
            ("MinL1", "red", "s"),
            ("MinSS", "green", "o"),
            ("MECO", "blue", "^"),
        ]

        # Left: P_succ vs λ (log x, linear y)
        ax0 = axes[0]
        ax0.set_xscale("log")
        ax0.set_xlim([1e-6, 1e-1])
        # y-limits are chosen to match your figure
        ax0.set_ylim([0.76, 0.82])
        ax0.grid(True, which="both", linestyle="-", alpha=0.3)
        for name, color, marker in style_order:
            ax0.plot(
                noise_levels,
                psucc_results[name],
                marker=marker,
                color=color,
                linewidth=1.5,
                label=name,
            )

    ax0.set_xlabel(r"Noise Level $\lambda$")
    ax0.set_ylabel(r"Success Probability $P_{\mathrm{succ}}$")
    ax0.legend(loc="lower left", frameon=True)

    # Right: L2 vs λ (log x, log y)
    ax1 = axes[1]
    ax1.set_xscale("log")
    ax1.set_yscale("log")
    ax1.set_xlim([1e-6, 1e-1])
    ax1.set_ylim([1e-7, 5e-2])
    ax1.grid(True, which="both", linestyle="-", alpha=0.3)
    for name, color, marker in style_order:
        ax1.plot(
            noise_levels,
            results_L2[name],
            marker=marker,
            color=color,
            linewidth=1.5,
            label=name,
        )
    ax1.set_xlabel(r"Noise Level $\lambda$")
    ax1.set_ylabel(r"$L_2$ Distance")
    ax1.legend(loc="upper left", frameon=True)

    plt.tight_layout()
    plt.savefig(fig_path, bbox_inches="tight")


if __name__=="__main__":
    sweep_FitQSD()